### ISSUE TITLE
Question about slideAnctionWithLoaderButton

### ISSUE THREAD

**Issue by NicosNicolaou16** [r1n1os/sliding_action_button#5]
Hello @r1n1os , thank you for the very useful package! 😃 My question is: how can we reset to the default state after the loader? For example, if we get an error from an API and want to slide it again, how can we do that?

**Comment by r1n1os** [comment]
Hello @NicosNicolaou16 and thank you for checking out my package! Nice question. Currently, there is not way to do this as my idea was to slide to perfom an action like redirection etc. But this is another good approach. 

Thank you for the feedback! 
I’ll review and implement this, and I’ll get back to you!

**Comment by r1n1os** [comment]
@NicosNicolaou16 Can you please add the code below into your pubspec.yaml file under dependencies:

```
 sliding_action_button:
   git:
     url: https://github.com/r1n1os/sliding_action_button.git
     ref: 7f2e3f61553c5efd325e21cdeafe13a58ea16e9d

```
Once you confirm I will release the version with the fix
